### PR TITLE
add square shape

### PR DESCRIPTION
**Pull request by dz-hexiang**
add square shape for some square point view

### CODE REVIEW

**Comment by TakuSemba** [comment]
Thank you for the PR, I added some comment.

**Comment by dz-hexiang** [comment]
Thank you！

**Comment by dz-hexiang** [comment]
when i change int to float，the animation realy got better  ，thank you very much！

**Comment by TakuSemba** [comment]
I think the points that i reviewed has not fixed yet.
I'm closing this issue due to inactivity.

**Pull request closed without merging**
